services:
  mysql:
    image: mysql:8.0
    container_name: mysql_lab
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: alerthub
      MYSQL_DATABASE: alerthub
      MYSQL_USER: alerthub
      MYSQL_PASSWORD: alerthub
    ports:
      - "33006:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
#
